export const RATE_LIMIT_OPTIONS = 'RATE_LIMIT_OPTIONS';
export const RATE_LIMIT_STORE = 'RATE_LIMIT_STORE';
export const RATE_LIMIT_DECORATOR = 'RATE_LIMIT_DECORATOR';
export const RATE_LIMIT_DECORATOR_LIMIT = 'RATE_LIMIT_DECORATOR_LIMIT';
export const RATE_LIMIT_DECORATOR_TIME_SLOT = 'RATE_LIMIT_DECORATOR_TIME_SLOT';

export const DEFAULT_LIMIT = 5;
export const DEFAULT_TIME_SLOT = 600;
